cleanup wasta-reset for 22.04

diff --git a/install-files/bin/wasta-initial-setup b/install-files/bin/wasta-initial-setup
--- a/install-files/bin/wasta-initial-setup
+++ b/install-files/bin/wasta-initial-setup
@@ -176,22 +176,22 @@ then
     exit 1
 fi
 
-ADJUST_SCRIPT=/usr/share/wasta-multidesktop/scripts/app-adjustments.sh
-if [ -e "$ADJUST_SCRIPT" ];
-then
-    echo
-    echo "*** Calling app-adjustments.sh script"
-    echo
-    bash $ADJUST_SCRIPT $AUTO
-    LASTERRORLEVEL=$?
-    if [ "$LASTERRORLEVEL" -ne "0" ];
-    then
-        echo
-        echo " *** ERROR in return from app-adjustments.sh. Exiting."
-        echo
-        exit 1
-    fi
-fi
+#ADJUST_SCRIPT=/usr/share/wasta-multidesktop/scripts/app-adjustments.sh
+#if [ -e "$ADJUST_SCRIPT" ];
+#then
+#    echo
+#    echo "*** Calling app-adjustments.sh script"
+#    echo
+#    bash $ADJUST_SCRIPT $AUTO
+#    LASTERRORLEVEL=$?
+#    if [ "$LASTERRORLEVEL" -ne "0" ];
+#    then
+#        echo
+#        echo " *** ERROR in return from app-adjustments.sh. Exiting."
+#        echo
+#        exit 1
+#    fi
+#fi
 
 echo
 echo "*** Running wasta-enable-zswap"
