adding wasta-remove-snaps and not installing Bloom to reduce ISO size

diff --git a/install-files/bin/wasta-initial-setup b/install-files/bin/wasta-initial-setup
--- a/install-files/bin/wasta-initial-setup
+++ b/install-files/bin/wasta-initial-setup
@@ -240,6 +240,22 @@ then
     exit 1
 fi
 
+if [ -x /usr/bin/snap ];
+then
+    echo
+    echo "*** Removing installed snaps to reduce ISO size"
+    echo
+    bash wasta-remove-snaps $AUTO
+    LASTERRORLEVEL=$?
+    if [ "$LASTERRORLEVEL" -ne "0" ];
+    then
+        echo
+        echo " *** ERROR in return from wasta-remove-snaps. Exiting."
+        echo
+        exit 1
+    fi
+fi
+
 # ------------------------------------------------------------------------------
 # Finished
 # ------------------------------------------------------------------------------
