add wasta-disable-hwe script

diff --git a/install-files/bin/wasta-initial-setup b/install-files/bin/wasta-initial-setup
--- a/install-files/bin/wasta-initial-setup
+++ b/install-files/bin/wasta-initial-setup
@@ -228,23 +228,17 @@ echo
 sed -i -e "s@.*\(KillUserProcesses\).*@\1=yes@" /etc/systemd/logind.conf
 
 echo
-echo "*** REMOVING HWE stack for 22.04.1"
+echo "*** Running wasta-disable-hwe"
 echo
-if ! [ "$AUTO" ];
+bash wasta-disable-hwe $AUTO
+LASTERRORLEVEL=$?
+if [ "$LASTERRORLEVEL" -ne "0" ];
 then
-    echo "Close this window if you do not want to remove the HWE stack."
     echo
-    read -p "Press <Enter> to continue..."
+    echo " *** ERROR in return from wasta-disable-hwe. Exiting."
+    echo
+    exit 1
 fi
-
-$DEBIAN_NONINERACTIVE bash -c "apt-get $YES install \
-    linux-generic"
-
-$DEBIAN_NONINERACTIVE bash -c "apt-get $YES purge \
-    linux-generic-hwe-22.04 \
-    linux-headers-generic-hwe-22.04 \
-    linux-image-generic-hwe-22.04"
-
 
 # ------------------------------------------------------------------------------
 # Finished
